# Generated by Django 2.2.16 on 2020-10-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPpopUpWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.ImageField(upload_to=''),
        ),
    ]
